version: '2'

networks:
  testbed:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.1
    restart: always
    networks:
      - testbed
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:3.2.1
    restart: always
    networks:
      - testbed
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

